
Ejercicio 1
Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por filas (1,2,3,4...).

In [3]:
import numpy as np
A= np.arange(1,65,1)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


In [4]:
M= np.reshape(A,(8,8))
print(M)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


Ejercicio 2:
i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

ii. reemplazar los elementos que tengan al menos un 3 por -99.

In [5]:
M2= np.transpose(M)
print(M2)

[[ 1  9 17 25 33 41 49 57]
 [ 2 10 18 26 34 42 50 58]
 [ 3 11 19 27 35 43 51 59]
 [ 4 12 20 28 36 44 52 60]
 [ 5 13 21 29 37 45 53 61]
 [ 6 14 22 30 38 46 54 62]
 [ 7 15 23 31 39 47 55 63]
 [ 8 16 24 32 40 48 56 64]]


In [6]:
for i in range(8):
    for j in range(8):
        e= str(M[i][j])
        o = e.find('3')
        if (o != -1):
            M[i][j] = -99
print(M)

[[  1   2 -99   4   5   6   7   8]
 [  9  10  11  12 -99  14  15  16]
 [ 17  18  19  20  21  22 -99  24]
 [ 25  26  27  28  29 -99 -99 -99]
 [-99 -99 -99 -99 -99 -99 -99  40]
 [ 41  42 -99  44  45  46  47  48]
 [ 49  50  51  52 -99  54  55  56]
 [ 57  58  59  60  61  62 -99  64]]
